

services:

  server:
    build:
      context: ./server
  client:
    build: 
      context: ./client

  test_server:
    build:
      context: ./test_server/
    environment:
      URI_SERVER: http://server:8000
    volumes:
      - ${PWD}/test_server/reports:/pytest/reports:rw
    links:
        - server

  test_client:
    links:
        - server
        - client
    environment:
      #- DISPLAY
      - CYPRESS_BASE_URL=https://bug-free-acorn-r56q9wg9rwg25r46-8001.app.github.dev/?api=https://bug-free-acorn-r56q9wg9rwg25r46-8000.app.github.dev
    #user: ${USER}  # ummm, problems with user on cypress startup

